INSERT INTO ROL (IDROL, DESCROL) VALUES ('4', 'Auxiliar');
INSERT INTO SEDE (IDSEDE, NOMBRESEDE, DIRECCIONSEDE) VALUES ('s3','Bosa','cll52 sur #93d -39');
INSERT INTO SEDE (IDSEDE, NOMBRESEDE, DIRECCIONSEDE) VALUES ('s4','Tecnologica','cll 68d bis a sur #49f-70');
INSERT INTO SEDE (IDSEDE, NOMBRESEDE, DIRECCIONSEDE) VALUES ('s5','ASAB','cll13 #14-69');